import 'dotenv/config';
import express from 'express'; import helmet from 'helmet'; import cookieParser from 'cookie-parser';
import crypto from 'node:crypto'; import fs from 'node:fs'; import path from 'node:path'; import {fileURLToPath} from 'node:url';
import {createDatabase} from './db.js';

const root=path.dirname(fileURLToPath(import.meta.url)),app=express(),db=createDatabase(process.env.DB_PATH);
const videos=JSON.parse(fs.readFileSync(path.join(root,'videos.json'),'utf8')).map(v=>({...v,category:v.category||(v.id<=15?'individual':'team')}));
const videoById=new Map(videos.map(v=>[v.id,v])),secret=process.env.APP_SECRET||'development-only-secret-change-before-deploy';
const activityStart=new Date(process.env.ACTIVITY_START||'2026-10-12T10:00:00+08:00'),activityEnd=new Date(process.env.ACTIVITY_END||'2026-10-23T17:00:00+08:00');
const ACTIVE="('valid','flagged')",mutationWindows=new Map();
if(process.env.NODE_ENV==='production'){if(secret.startsWith('development-'))throw new Error('Production requires APP_SECRET.');if(!process.env.RECAPTCHA_SITE_KEY||!process.env.RECAPTCHA_SECRET_KEY)throw new Error('Production requires reCAPTCHA keys.')}
if(process.env.TRUST_PROXY==='1')app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'20kb'}));app.use(cookieParser());app.use(express.static(path.join(root,'public')));

const nowIso=()=>new Date().toISOString(),hash=v=>crypto.createHmac('sha256',secret).update(String(v||'')).digest('hex'),sign=v=>`${v}.${hash(v)}`;
const unsign=s=>{if(!s?.includes('.'))return null;const i=s.lastIndexOf('.'),v=s.slice(0,i),sig=s.slice(i+1),expected=hash(v);return sig.length===expected.length&&crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))?v:null};
const state=()=>new Date()<activityStart?'upcoming':new Date()>activityEnd?'ended':'active';
const activity=()=>({state:state(),startsAt:activityStart.toISOString(),endsAt:activityEnd.toISOString()});
function device(req,res){let id=unsign(req.cookies.vote_device);if(!id){id=crypto.randomUUID();res.cookie('vote_device',sign(id),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:365*86400_000})}const now=nowIso();db.prepare('INSERT INTO devices(id,created_at,last_seen_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen_at=excluded.last_seen_at').run(id,now,now);return id}
const activeVotes=id=>db.prepare(`SELECT id,video_id videoId,category,status,created_at createdAt FROM votes WHERE device_id=? AND status IN ${ACTIVE} ORDER BY created_at`).all(id);
const qualification=(id,videoId)=>db.prepare('SELECT id FROM watch_sessions WHERE device_id=? AND video_id=? AND qualified_at IS NOT NULL ORDER BY qualified_at DESC LIMIT 1').get(id,videoId);
const audit=(action,target,detail={})=>db.prepare('INSERT INTO audit_logs(action,target,detail,created_at) VALUES(?,?,?,?)').run(action,target,JSON.stringify(detail),nowIso());
function rateLimit(req,id){const now=Date.now(),keys=[[`d:${id}`,10],[`i:${hash(req.ip)}`,30]];for(const [key,limit] of keys){const recent=(mutationWindows.get(key)||[]).filter(t=>now-t<60000);if(recent.length>=limit)return false;recent.push(now);mutationWindows.set(key,recent)}return true}
async function captcha(token,ip){if(process.env.NODE_ENV==='test')return token==='test-pass';if(!process.env.RECAPTCHA_SECRET_KEY)return process.env.NODE_ENV!=='production'&&token==='development-pass';if(!token)return false;try{const body=new URLSearchParams({secret:process.env.RECAPTCHA_SECRET_KEY,response:token,remoteip:ip});const response=await fetch('https://www.google.com/recaptcha/api/siteverify',{method:'POST',body,signal:AbortSignal.timeout(8000)}),result=await response.json(),expected=process.env.RECAPTCHA_EXPECTED_HOSTNAME;return Boolean(result.success&&(!expected||result.hostname===expected||result.hostname==='localhost'))}catch{return false}}
function risk(req,id,signal){const ipHash=hash(req.ip),signalHash=signal?hash(signal):null,recentIp=db.prepare("SELECT COUNT(*) count FROM votes WHERE ip_hash=? AND created_at>=datetime('now','-10 minutes')").get(ipHash).count,others=signalHash?db.prepare('SELECT COUNT(DISTINCT device_id) count FROM votes WHERE device_signal_hash=? AND device_id<>?').get(signalHash,id).count:0,score=Math.min(100,Math.max(0,(recentIp-20)*4+others*25));return {ipHash,signalHash,score,status:score>=60?'flagged':'valid',recentIp,others}}
function validate(id,videoId,replacingId=null){const video=videoById.get(videoId);if(!video)return {error:'找不到這支作品。'};const votes=activeVotes(id);if(votes.some(v=>v.videoId===videoId&&v.id!==replacingId))return {error:'你已經投過這支作品。'};if(votes.filter(v=>v.category===video.category&&v.id!==replacingId).length>=2)return {error:`${video.category==='individual'?'個人組':'團體組'}已使用兩票，請選擇要改投的作品。`};const watch=qualification(id,videoId);return watch?{video,watch}:{error:'請先有效觀看這支影片達 80%。'}}

app.get('/api/bootstrap',(req,res)=>{const id=device(req,res),votes=activeVotes(id),used={individual:0,team:0};votes.forEach(v=>used[v.category]++);const progress=db.prepare('SELECT video_id videoId,MAX(watched_seconds/duration) ratio,MAX(qualified_at IS NOT NULL) qualified FROM watch_sessions WHERE device_id=? GROUP BY video_id').all(id);res.json({videos,votes,progress,limits:{individual:2,team:2},remaining:{individual:2-used.individual,team:2-used.team},activity:activity(),recaptchaSiteKey:process.env.RECAPTCHA_SITE_KEY||'',demo:false})});
app.post('/api/watch/start',(req,res)=>{const id=device(req,res),videoId=Number(req.body.videoId),duration=Number(req.body.duration);if(!videoById.has(videoId)||!Number.isFinite(duration)||duration<10||duration>7200)return res.status(400).json({error:'影片資料不正確。'});const session=crypto.randomUUID();db.prepare('INSERT INTO watch_sessions(id,device_id,video_id,duration,last_ping_at,created_at) VALUES(?,?,?,?,?,?)').run(session,id,videoId,duration,Date.now(),nowIso());res.json({sessionId:sign(session)})});
app.post('/api/watch/progress',(req,res)=>{const id=device(req,res),sessionId=unsign(req.body.sessionId),s=sessionId&&db.prepare('SELECT * FROM watch_sessions WHERE id=? AND device_id=?').get(sessionId,id);if(!s)return res.status(404).json({error:'觀看紀錄已失效，請重新播放。'});const pos=Number(req.body.position),rate=Number(req.body.playbackRate),wall=Math.max(0,Math.min((Date.now()-s.last_ping_at)/1000,8)),delta=pos-s.last_position,plausible=req.body.playing===true&&req.body.visible===true&&rate>0&&rate<=1.25&&delta>=0&&delta<=wall*1.6+1,watched=Math.min(s.duration,s.watched_seconds+(plausible?Math.min(wall,delta+.5):0)),qualified=watched/s.duration>=.8;db.prepare('UPDATE watch_sessions SET watched_seconds=?,last_position=?,last_ping_at=?,qualified_at=COALESCE(qualified_at,?) WHERE id=?').run(watched,Number.isFinite(pos)?pos:s.last_position,Date.now(),qualified?nowIso():null,sessionId);res.json({ratio:watched/s.duration,qualified})});

app.post('/api/votes',async(req,res)=>{const id=device(req,res);if(state()!=='active')return res.status(403).json({error:'目前不在投票期間。'});if(!rateLimit(req,id))return res.status(429).json({error:'操作過於頻繁，請稍後再試。'});if(!await captcha(req.body.recaptchaToken,req.ip))return res.status(403).json({error:'機器人驗證未通過，請重新勾選。'});const checked=validate(id,Number(req.body.videoId));if(checked.error)return res.status(409).json({error:checked.error});const r=risk(req,id,req.body.deviceSignal);try{const info=db.prepare('INSERT INTO votes(device_id,video_id,category,watch_session_id,ip_hash,device_signal_hash,risk_score,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,checked.video.id,checked.video.category,checked.watch.id,r.ipHash,r.signalHash,r.score,r.status,nowIso());if(r.score)db.prepare('INSERT INTO risk_events(device_id,ip_hash,kind,detail,created_at) VALUES(?,?,?,?,?)').run(id,r.ipHash,'vote_risk',JSON.stringify(r),nowIso());audit('create_vote',`vote:${info.lastInsertRowid}`,{videoId:checked.video.id,status:r.status});res.status(201).json({id:Number(info.lastInsertRowid),status:r.status})}catch(e){if(e.code?.startsWith('SQLITE_CONSTRAINT'))return res.status(409).json({error:'投票狀態已變更，請重新整理。'});throw e}});
app.post('/api/votes/:id/replace',async(req,res)=>{const id=device(req,res);if(state()!=='active')return res.status(403).json({error:'目前不在投票期間。'});if(!rateLimit(req,id))return res.status(429).json({error:'操作過於頻繁，請稍後再試。'});if(!await captcha(req.body.recaptchaToken,req.ip))return res.status(403).json({error:'機器人驗證未通過，請重新勾選。'});const old=db.prepare(`SELECT * FROM votes WHERE id=? AND device_id=? AND status IN ${ACTIVE}`).get(Number(req.params.id),id);if(!old)return res.status(404).json({error:'找不到可改投的票。'});const checked=validate(id,Number(req.body.videoId),old.id);if(checked.error)return res.status(409).json({error:checked.error});if(checked.video.category!==old.category)return res.status(400).json({error:'只能改投同一組別的作品。'});const r=risk(req,id,req.body.deviceSignal);try{const newId=db.transaction(()=>{const info=db.prepare('INSERT INTO votes(device_id,video_id,category,watch_session_id,ip_hash,device_signal_hash,risk_score,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,checked.video.id,checked.video.category,checked.watch.id,r.ipHash,r.signalHash,r.score,r.status,nowIso());db.prepare("UPDATE votes SET status='cancelled',cancelled_at=?,replaced_by_vote_id=? WHERE id=?").run(nowIso(),info.lastInsertRowid,old.id);audit('replace_vote',`vote:${old.id}`,{fromVideoId:old.video_id,toVideoId:checked.video.id,newVoteId:Number(info.lastInsertRowid)});return Number(info.lastInsertRowid)})();res.status(201).json({id:newId,status:r.status})}catch(e){if(e.code?.startsWith('SQLITE_CONSTRAINT'))return res.status(409).json({error:'改投失敗，原票仍然保留，請重新整理。'});throw e}});
app.delete('/api/votes/:id',(req,res)=>{const id=device(req,res);if(state()!=='active')return res.status(403).json({error:'投票截止後不能取消。'});if(!rateLimit(req,id))return res.status(429).json({error:'操作過於頻繁，請稍後再試。'});const result=db.prepare(`UPDATE votes SET status='cancelled',cancelled_at=? WHERE id=? AND device_id=? AND status IN ${ACTIVE}`).run(nowIso(),Number(req.params.id),id);if(!result.changes)return res.status(404).json({error:'找不到可取消的票。'});audit('cancel_vote',`vote:${req.params.id}`);res.json({ok:true})});
app.get('/api/results',(req,res)=>{const counts=new Map(db.prepare("SELECT video_id videoId,COUNT(*) count FROM votes WHERE status='valid' GROUP BY video_id").all().map(r=>[r.videoId,r.count])),ranked=category=>videos.filter(v=>v.category===category).map(v=>({...v,votes:counts.get(v.id)||0})).sort((a,b)=>b.votes-a.votes||a.id-b.id).map((v,i)=>({...v,rank:i+1}));res.json({published:state()==='ended',live:state()!=='ended',generatedAt:nowIso(),activity:activity(),groups:{individual:ranked('individual'),team:ranked('team')}})});

function requireAdmin(req,res,next){const supplied=req.get('x-admin-key')||'',expected=process.env.ADMIN_KEY||'';if(!expected||supplied.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected)))return res.status(401).json({error:'未授權。'});next()}
app.get('/api/admin/summary',requireAdmin,(req,res)=>res.json({totals:db.prepare('SELECT video_id videoId,status,COUNT(*) count FROM votes GROUP BY video_id,status ORDER BY video_id').all(),flagged:db.prepare("SELECT id,video_id videoId,risk_score riskScore,status,created_at createdAt FROM votes WHERE status!='valid' ORDER BY created_at DESC LIMIT 200").all()}));
app.post('/api/admin/votes/:id/void',requireAdmin,(req,res)=>{const reason=String(req.body.reason||'').trim().slice(0,300);if(!reason)return res.status(400).json({error:'請填寫作廢原因。'});const result=db.prepare("UPDATE votes SET status='void',voided_at=?,void_reason=? WHERE id=? AND status!='void'").run(nowIso(),reason,req.params.id);if(!result.changes)return res.status(404).json({error:'找不到可作廢的票。'});audit('void_vote',`vote:${req.params.id}`,{reason});res.json({ok:true})});
app.use((error,req,res,next)=>{console.error(error);res.status(500).json({error:'系統暫時無法處理，請稍後再試。'})});
if(process.env.NODE_ENV!=='test')app.listen(Number(process.env.PORT||3000),()=>console.log(`Voting site: http://localhost:${process.env.PORT||3000}`));
export {app,db};
